//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorsHelper.Dictionaries.Data.EFCore.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoctorsHelper.Dictionaries.Data.EFCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [{&quot;Id&quot;:1,&quot;Pathology&quot;:&quot;Врожденные пороки развития, деформации, хромосомные аномалии со стойкими значительными нарушениями функции органов и систем&quot;},{&quot;Id&quot;:2,&quot;Pathology&quot;:&quot;Последствия повреждений центральной и периферической нервной системы, внутренних органов, костно-мышечной системы и соединительной ткани от воздействия внешних факторов(травмы, радиация, термическое, химическое и другое воздействие и т.д.) с развитием необратимых изменений, вызвавших нарушения функции органов и систем значительной степени&quot;}, [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string GeneralMedicalContraindicationDataJson {
            get {
                return ResourceManager.GetString("GeneralMedicalContraindicationDataJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [{&quot;Id&quot;:1,&quot;Code&quot;:&quot;A00&quot;,&quot;Name&quot;:&quot;Холера&quot;},{&quot;Id&quot;:2,&quot;Code&quot;:&quot;A00.0&quot;,&quot;Name&quot;:&quot;Холера, вызванная вибрионом 01, биовар cholerae&quot;},{&quot;Id&quot;:3,&quot;Code&quot;:&quot;A00.1&quot;,&quot;Name&quot;:&quot;Холера, вызванная вибрионом 01, биовар eltor&quot;},{&quot;Id&quot;:4,&quot;Code&quot;:&quot;A00.9&quot;,&quot;Name&quot;:&quot;Холера неуточненная&quot;},{&quot;Id&quot;:5,&quot;Code&quot;:&quot;A01&quot;,&quot;Name&quot;:&quot;Тиф и паратиф&quot;},{&quot;Id&quot;:6,&quot;Code&quot;:&quot;A01.0&quot;,&quot;Name&quot;:&quot;Брюшной тиф&quot;},{&quot;Id&quot;:7,&quot;Code&quot;:&quot;A01.1&quot;,&quot;Name&quot;:&quot;Паратиф А&quot;},{&quot;Id&quot;:8,&quot;Code&quot;:&quot;A01.2&quot;,&quot;Name&quot;:&quot;Паратиф В&quot;},{&quot;Id&quot;:9,&quot;Code&quot;:&quot;A01.3&quot;,&quot;Name&quot;:&quot;Паратиф С&quot;},{&quot;Id&quot;:10,&quot;Code&quot;:&quot;A01.4&quot;,&quot;Name&quot;:&quot;Паратиф не [остаток стро....
        /// </summary>
        internal static string Mkb10RecordDataJson {
            get {
                return ResourceManager.GetString("Mkb10RecordDataJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [{&quot;Id&quot;:2082,&quot;Point&quot;:&quot;1.1.1.&quot;,&quot;Name&quot;:&quot;Аллергены, \&quot;А\&quot;&quot;,&quot;InspectionFrequency&quot;:&quot;1 раз в год&quot;,&quot;AdditionalMedicalContraindications&quot;:&quot;Аллергические заболевания различных органов и систем#&quot;,&quot;ApplicationItemNumber&quot;:1},{&quot;Id&quot;:2083,&quot;Point&quot;:&quot;1.1.2.&quot;,&quot;Name&quot;:&quot;Канцерогены, \&quot;К\&quot;&quot;,&quot;InspectionFrequency&quot;:&quot;1 раз в год&quot;,&quot;AdditionalMedicalContraindications&quot;:&quot;Доброкачественные новообразования любой локализации, склонные к перерождению#&quot;,&quot;ApplicationItemNumber&quot;:1},{&quot;Id&quot;:2084,&quot;Point&quot;:&quot;1.1.3.&quot;,&quot;Name&quot;:&quot;Химические вещества, оказываю [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Order302NRecordDataJson {
            get {
                return ResourceManager.GetString("Order302NRecordDataJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [{&quot;Id&quot;:1,&quot;Point&quot;:&quot;1.1. &quot;,&quot;Nosology&quot;:&quot;Острое отравление этанолом (проявления: расстройство вегетативной (автономной) нервной системы, токсическая энцефалопатия, делирий, галлюциноз, кома токсическая)&quot;,&quot;CodeNosology&quot;:&quot;T51.0#&quot;,&quot;DangerFactor&quot;:&quot;Этанол&quot;,&quot;CodeExternal&quot;:&quot;Y96 &quot;},{&quot;Id&quot;:2,&quot;Point&quot;:&quot;1.2. &quot;,&quot;Nosology&quot;:&quot;Острое отравление спиртами (за исключением этанола) (проявления: расстройство вегетативной (автономной) нервной системы, токсическая энцефалопатия, делирий, галлюциноз, кома токсическая, при интоксикации м [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Order417NRecordDataJson {
            get {
                return ResourceManager.GetString("Order417NRecordDataJson", resourceCulture);
            }
        }
    }
}
